---
# tasks file for vsftpd
- name: Install vsftpd package
  yum:
    name: vsftpd
    state: latest

- name: Copy customized config
  template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd/vsftpd.conf
  notify: Restart vsftpd

- name: Enable and start vsftpd service
  service:
    name: vsftpd
    enabled: yes
    state: started

- name: Enable and start firewalld
  service:
    name: firewalld
    enabled: yes
    state: started

- name: Enable ftp service network access
  firewalld:
    service: ftp
    permanent: yes
    state: enabled
  notify: Reload firewalld rules
